#DECLARATION DES PREFIXES
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX moi: <http://www.semanticweb.org/germain/ontologies/2016/10/CLAUSS_SAINTIER_Sports#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

#REQUETE 1 : Sportifs et leurs nationalités.
SELECT ?a ?b
WHERE { 
	?a moi:personneANationalite ?b ;
	moi:personneAPlace ?c
} ORDER BY ?a

#REQUETE 2 : Intitulés de tous les événements sportifs répertoriés pour l'année 2016
SELECT ?intitule_evenement
WHERE {
	?x moi:evenementAIntitule ?intitule_evenement;
	moi:evenementAAnnee 2016
}

#REQUETE 3 : Tous les noms de famille de sportifs commençant par m (ou M), triés par ordre alphabétique.
SELECT ?nom
WHERE
{
    ?x moi:personneAPlace ?c .
    ?x foaf:lastName ?nom .
    FILTER regex(?nom, "^m", "i") .
}
ORDER BY ?nom
